### ISSUE TITLE
plaintext language list in top left needs to be removed

### ISSUE THREAD

**Issue by Derekf5** [getlantern/www#19]
language options appear in plaintext in top left.
<img width="1270" alt="screen shot 2015-07-18 at 5 00 34 pm" src="https://cloud.githubusercontent.com/assets/7864729/8763563/29f0e78c-2d71-11e5-9964-75d9209b1a5f.png">

**Comment by velvetlicious** [comment]
José needs to add the url to the file, that's why the button isn't working

**Comment by xiam** [comment]
Thanks @velvetlicious! I think it's working now, could you test it @Derekf5?

![screen shot 2015-07-18 at 6 23 24 pm](https://cloud.githubusercontent.com/assets/385670/8763910/19a5cc5e-2d7a-11e5-9472-539f753c665a.png)

**Comment by atavism** [comment]
Nice. I like how that looks. It's working for me!

**Comment by Derekf5** [comment]
Looks good to me, i am going to close this issue
