### ISSUE TITLE
Missing translation in "how" section

### ISSUE THREAD

**Issue by fffw** [getlantern/www#23]
"Lantern is an internet proxy tool that lets you access blocked sites.". "Internet" should be capitalized.

**Comment by Derekf5** [comment]
@fffw @atavism or @xiam  if i change the capitalization issue in the JSON file will it change one the site?

**Comment by fffw** [comment]
It will. I made the change and will create a PR

**Comment by fffw** [comment]
PR at https://github.com/getlantern/www/pull/25
