### ISSUE TITLE
Link shows up on button in translated version of the site.

### ISSUE THREAD

**Issue by Derekf5** [getlantern/www#24]
This could be because some things are linked in the Json translation file.   If i remove it, it should fix correct @atavism @xiam ?
<img width="755" alt="screen shot 2015-07-19 at 10 36 02 am" src="https://cloud.githubusercontent.com/assets/7864729/8766362/d4019cf8-2e02-11e5-9f4e-9cc8f2c03302.png">

**Comment by fffw** [comment]
@Derekf5 Yes exactly. The translation file has already updated and the link was removed.

**Comment by Derekf5** [comment]
Cool, Thanks @fffw! when will the new code appear at 45.55.228.157

**Comment by xiam** [comment]
It takes a few minutes :)

**Comment by xiam** [comment]
Looks good to me now.
