### ISSUE TITLE
The Language selection dropdown looks like a search box

### ISSUE THREAD

**Issue by sheena3** [getlantern/www#32]
Make English as default language so that it will be easy for the users to recognize the dropdown as to select the language.

**Comment by myleshorton** [comment]
Yeah I kind of agree. What do you think @Derekf5 and @carsonefv?

**Comment by Derekf5** [comment]
On chrome and safari for me it appears with arrows to indicate a dropdown, and has english as the default language, @sheena3 @myleshorton what browser does it look strange to you on?  could you provide a screenshot?

**Comment by sheena3** [comment]
I am using Windows 8.1 and it doesn't show what is the current language(English) in the dropdown. Also in IE 11, the dropdown doesn't even has the arrow.

Chrome browser:
![windows - chrome](https://cloud.githubusercontent.com/assets/11394369/8913198/2b884cd4-34b5-11e5-8287-316d107b4d74.png)

Firefox bowser:
![windows - firefox](https://cloud.githubusercontent.com/assets/11394369/8913199/2b895a98-34b5-11e5-88f1-71df6eb4f157.png)

IE
![windows- ie 11](https://cloud.githubusercontent.com/assets/11394369/8913200/2b8ba618-34b5-11e5-8c58-e4653e6d9b83.png)

**Comment by Derekf5** [comment]
Thanks @sheena3. i def think those shots look off. this is how it appears on mac in chrome.  I think if we can get the browsers on windows to appear this way we will be in good shape.  @myleshorton who should we assign to this to fix? Thanks all!
<img width="1774" alt="screen shot 2015-07-27 at 1 48 34 pm" src="https://cloud.githubusercontent.com/assets/7864729/8913311/512df65e-3466-11e5-9eb8-ff1f3c032cda.png">

**Comment by myleshorton** [comment]
@xiam can we get your friend to fix this one?

**Comment by xiam** [comment]
@myleshorton This is an easy one, I can fix it right away.

**Comment by Derekf5** [comment]
thanks @xiam!

**Comment by xiam** [comment]
It should be better now @sheena3, see http://d3f69bko3qnt7.cloudfront.net/

I also pushed it to S3 but I think it will take some time for the cache to get refreshed, right @myleshorton?

**Comment by myleshorton** [comment]
You currently have to manually invalidate the current distribution at https://console.aws.amazon.com/cloudfront/home?region=us-east-1#distribution-settings:E1UX00QZB0FGKH

I just created an invalidation for /static/js/main.js and /static/css/main.css

**Comment by xiam** [comment]
Thanks @myleshorton! Dear @sheena3, could you check again?

**Comment by sheena3** [comment]
Awesome! Looks good now..closing. Thanks all!
