### ISSUE TITLE
Add Google Play badge to website

### ISSUE THREAD

**Issue by atavism** [getlantern/www#53]
Now that [Lantern has been published to the Google Play store](https://play.google.com/store/apps/details?id=org.getlantern.lantern), we should add a "Get it on Google Play" badge to the website that points to it.

![image](https://cloud.githubusercontent.com/assets/6346213/15102179/0f5a8716-1551-11e6-95c9-c20fffd0e0f6.png)

https://play.google.com/intl/en_us/badges/

**Comment by fffw** [comment]
I can work on it

**Comment by atavism** [comment]
Thanks, @fffw!! Looks great
